'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'

interface ResumeData {
  name: string
  position: string
  skills: string
  experience: string
}

interface Template {
  id: string
  name: string
  emoji: string
  preview: string
}

const TEMPLATES: Template[] = [
  {
    id: 'modern',
    name: 'Modern',
    emoji: '📄',
    preview: 'Clean · Left sidebar · Professional',
  },
  {
    id: 'classic',
    name: 'Classic',
    emoji: '📋',
    preview: 'Traditional · Header layout · Serif',
  },
  {
    id: 'creative',
    name: 'Creative',
    emoji: '🎨',
    preview: 'Colorful accents · Modern · Bold',
  },
]

export default function ResumePage() {
  const t = useTranslations('resume')
  const [selectedTemplate, setSelectedTemplate] = useState('modern')
  const [formData, setFormData] = useState<ResumeData>({
    name: '',
    position: '',
    skills: '',
    experience: '',
  })
  const [generating, setGenerating] = useState(false)
  const [result, setResult] = useState<string | null>(null)
  const [error, setError] = useState('')

  const handleChange = (field: keyof ResumeData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
    setResult(null)
  }

  const handleGenerate = async () => {
    if (!formData.name.trim()) {
      setError(t('nameRequired'))
      return
    }
    setError('')
    setGenerating(true)
    setResult(null)

    // Simulate generation
    try {
      await new Promise((resolve) => setTimeout(resolve, 1800))

      const templateName =
        TEMPLATES.find((tpl) => tpl.id === selectedTemplate)?.name || 'Modern'
      const generated = `
        <div style="background:white;padding:32px;border-radius:16px;border:1px solid #e5e7eb;">
          <div style="text-align:center;margin-bottom:24px;">
            <h1 style="font-size:28px;font-weight:800;color:#1e293b;margin:0;">${formData.name}</h1>
            <p style="font-size:16px;color:#6366f1;font-weight:500;margin:4px 0 0 0;">${formData.position || 'Professional'}</p>
          </div>
          <hr style="border:none;border-top:2px solid #e5e7eb;margin:16px 0;" />
          <section style="margin-bottom:16px;">
            <h2 style="font-size:16px;font-weight:700;color:#1e293b;margin:0 0 8px 0;">Skills</h2>
            <p style="font-size:14px;color:#475569;line-height:1.6;margin:0;">${formData.skills || '—'}</p>
          </section>
          <section>
            <h2 style="font-size:16px;font-weight:700;color:#1e293b;margin:0 0 8px 0;">Experience</h2>
            <p style="font-size:14px;color:#475569;line-height:1.6;margin:0;white-space:pre-wrap;">${formData.experience || '—'}</p>
          </section>
          <div style="margin-top:20px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12px;color:#94a3b8;text-align:center;">
            Template: ${templateName} · Generated by AI Toolbox
          </div>
        </div>
      `
      setResult(generated)
    } catch {
      setError('Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="page-container">
      <div className="page-header">
        <span className="page-header-icon">📝</span>
        <h1 className="page-header-title">{t('title')}</h1>
        <p className="page-header-desc">{t('desc')}</p>
      </div>

      {/* Template selector */}
      <div className="mb-6">
        <h3 className="text-sm font-medium text-gray-500 mb-3">
          {t('template')}
        </h3>
        <div className="grid grid-cols-3 gap-3">
          {TEMPLATES.map((tpl) => (
            <button
              key={tpl.id}
              onClick={() => {
                setSelectedTemplate(tpl.id)
                setResult(null)
              }}
              className={`content-card p-4 text-center transition-all duration-200 ${
                selectedTemplate === tpl.id
                  ? 'ring-2 ring-indigo-500 border-indigo-300 bg-indigo-50'
                  : 'hover:border-indigo-200 hover:shadow-sm'
              }`}
            >
              <span className="text-3xl block mb-1">{tpl.emoji}</span>
              <span className="text-sm font-semibold text-gray-800 block">
                {tpl.name}
              </span>
              <span className="text-[11px] text-gray-400 block mt-1">
                {tpl.preview}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Form */}
      <div className="content-card p-4 sm:p-6 mb-6">
        <h3 className="text-sm font-medium text-gray-500 mb-4">
          {t('basicInfo')}
        </h3>
        <div className="space-y-4">
          <div>
            <input
              type="text"
              value={formData.name}
              onChange={(e) => handleChange('name', e.target.value)}
              placeholder={t('namePlaceholder')}
              className="input-base"
            />
          </div>
          <div>
            <input
              type="text"
              value={formData.position}
              onChange={(e) => handleChange('position', e.target.value)}
              placeholder={t('positionPlaceholder')}
              className="input-base"
            />
          </div>
          <div>
            <input
              type="text"
              value={formData.skills}
              onChange={(e) => handleChange('skills', e.target.value)}
              placeholder={t('skillsPlaceholder')}
              className="input-base"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-500 mb-1.5">
              {t('experience')}
            </label>
            <textarea
              value={formData.experience}
              onChange={(e) => handleChange('experience', e.target.value)}
              rows={4}
              placeholder="Company Name · Position · Duration&#10;• Describe your achievements...&#10;• Use bullet points for clarity"
              className="input-base resize-none min-h-[100px]"
            />
          </div>
        </div>
      </div>

      {/* Generate button */}
      <button
        onClick={handleGenerate}
        disabled={generating}
        className="btn-primary mb-6"
      >
        {generating ? (
          <span className="flex items-center justify-center gap-2">
            <svg
              className="animate-spin h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
              />
            </svg>
            Generating...
          </span>
        ) : (
          t('generate')
        )}
      </button>

      {/* Error */}
      {error && (
        <div className="mb-6 p-4 rounded-xl bg-red-50 border border-red-200 text-red-600 text-sm text-center">
          {error}
        </div>
      )}

      {/* Result */}
      {result && (
        <div className="animate-fade-in">
          <div className="content-card p-4 sm:p-6 mb-4">
            <div dangerouslySetInnerHTML={{ __html: result }} />
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => {
                const blob = new Blob([result], { type: 'text/html' })
                const url = URL.createObjectURL(blob)
                const a = document.createElement('a')
                a.href = url
                a.download = `${formData.name || 'resume'}.html`
                a.click()
                URL.revokeObjectURL(url)
              }}
              className="btn-secondary !w-auto px-6"
            >
              Download HTML
            </button>
            <button
              onClick={() => {
                navigator.clipboard.writeText(result)
              }}
              className="btn-secondary !w-auto px-6"
            >
              Copy HTML
            </button>
          </div>
        </div>
      )}
    </div>
  )
}